### ISSUE TITLE
Overlay box there after everything is removed and checked off

### ISSUE THREAD

**Issue by Combatt1ron** [cmsu224/clan-events#23]
![image](https://user-images.githubusercontent.com/114749774/193281008-ee5b02e3-be6c-49d0-ac0f-a72ab02c94a7.png)

Hi,

This has happened. Was trying to turn it off after a clan event just finished. I can create new ones just fine and remove them, but this one can't be removed?

Any ideas?

Thanks

**Comment by cmsu224** [comment]
Never seen that before.  Is it still there after you restart the client?

**Comment by Combatt1ron** [comment]
Yeah, tried resetting it and everything, Don't really want to unistall Runelite either lol.

Like I can create new ones just fine and remove them *shruggers*

**Comment by cmsu224** [comment]
Can you turn the plugin off, close runelite, open it again, and send me the log file?

**Comment by Combatt1ron** [comment]
Can do one better. 

![image](https://user-images.githubusercontent.com/114749774/193302739-2259b246-ccde-4054-92fb-e88f50ead4d8.png)

This seemed to have fixed the issue. Log file would have changed while sorting it out, but doing this makes it go away.
