### ISSUE TITLE
HTTP Request timed out

### ISSUE THREAD

**Issue by HeavensGatex** [cmsu224/clan-events#26]
Hi!

I tried setting up our clan events system since we are growing lately.
At the beginning, everything worked fine, but for some reason I receive the HTTP Request timed out.

This happend to me earlier when I change the group ID to our group.
I tried to change it back but the time out kept popping up.

This morning, my old file worked again, after making a few new changes and checking them, I received the timed out again.

Any clue what I'm doing wrong?
![image](https://user-images.githubusercontent.com/77594762/217231791-3ede5de3-eda6-4b2e-98b3-b315ce947616.png)

**Comment by HeavensGatex** [comment]
For some reason without changing anything, it started to work again. Not sure for how long, but i'm also missing data

I've been fishing to get some exp:
![image](https://user-images.githubusercontent.com/77594762/217247735-cde4bb1d-2e3a-4fb1-9118-851236409d0c.png)

But it doesnt show up in the plugin/spreadsheet.
![image](https://user-images.githubusercontent.com/77594762/217247839-ced90ae0-00af-464e-9d76-099245a223c8.png)
![image](https://user-images.githubusercontent.com/77594762/217248709-8f8f7631-3c4d-4470-a4d9-b7bfd4a02912.png)

After changing the "gain" column to view "Start-End exp", everything works fine:
![image](https://user-images.githubusercontent.com/77594762/217249023-f9cb07a5-19b8-46a1-8b26-73a6b28551e7.png)

**Comment by Alfradu** [comment]
@HeavensGatex we have rolled out a fix for this. This issue stemmed from how the data fetching was set up and has been reworked to never time out unless the google api really does time out (after a couple of min).

**Comment by HeavensGatex** [comment]
> @HeavensGatex we have rolled out a fix for this. This issue stemmed from how the data fetching was set up and has been reworked to never time out unless the google api really does time out (after a couple of min).

Thanks for your reply, but im still missing data for some reason.. As far as I could test it now:
![image](https://user-images.githubusercontent.com/77594762/224543667-48cb271b-ec38-4ff7-b9af-07063a53e296.png)
![image](https://user-images.githubusercontent.com/77594762/224543705-bd7d7ee4-2002-4713-a897-ab7744103bd2.png)

Changing column 3 to 4 does seem to work, but not in the way its intended: 
![image](https://user-images.githubusercontent.com/77594762/224543762-881890fa-be51-4f1f-ba97-2c45ee564cd8.png)

**Comment by Alfradu** [comment]
Could you share your sheet with me so i can try it out myself? or if you would like i could try and solve it with you via discord or something: sumaris#1256

**Comment by Alfradu** [comment]
Temporary solution seems to be to add more users to the templeosrs competition. A more permanent fix is to update the google sheet functions handling this in the hof_sotw_botw_data sheet to include a MAP() forcing all cell values to become text: QUERY(MAP(IMPORTHTML(Links!$B$11,"table",1), LAMBDA(item, JOIN("'", item))), "select Col1, Col2, Col3 limit 20")

**Comment by HeavensGatex** [comment]
Thanks for helping out @Alfradu !
