### ISSUE TITLE
Side panel stopped showing, 

### ISSUE THREAD

**Issue by datboioverthere** [cmsu224/clan-events#27]
Hello!

Ive been using the plugin with great fun but it seems that it suddenly stopped showing in the side panel about a week ago.
We have been using the plugin unedited with the sheet for a few months now and i really dont know what made it change.

There are no errors, the sidepanel menus are now just empty below the refresh button. Not even the big red error https messages.

![image](https://user-images.githubusercontent.com/91017857/225164909-c616ea4d-86f1-4c83-b428-996c5551c8dd.png)

**Comment by Alfradu** [comment]
We recently updated the plugin to fetch data from google sheets in a different way. No idea what could be wrong but if you want I can try and debug it with you. discord: sumaris#1256
