### ISSUE TITLE
Error Fetching Data!

### ISSUE THREAD

**Issue by HolyGoalie10** [cmsu224/clan-events#28]
Error Fetching Data!: Please wait a minute before trying again. The plugin was working great for me for several months, its now currently stuck doing this. I haven't made any changes to the sheet or API that I am aware of that would cause this. I have not tried changing the API key. Do you have any suggestions? I really love this plugin its been a treat to be able to use, so thankyou for making it available!

**Comment by cmsu224** [comment]
Its probably your google sheet.  Look at the example I have on the readMe page and make a copy of it for your use.
